apiVersion: v1
kind: Service
metadata:
  name: suppliers-service
spec:
  selector:
    app: suppliers
  ports:
    - protocol: TCP
      name: "80"
      port: 80
      targetPort: 80
  clusterIP: 10.96.0.4
  type: LoadBalancer
